import courseImage from "../assets/images/courses/calculus.jpg";
import avater from "../assets/images/courseAuthor/avater.png";

export const courses = [
  {
    id: 1,
    title: "Introduction to Programming",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore qui, aut odit, ullam eaque exercitationem cumque quae voluptas perferendis, atque repellat culpa quam ipsum quod.",
    image: courseImage,
  },
  {
    id: 2,
    title: "Web Development",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Build modern websites with HTML, CSS, and JavaScript.",
    image: courseImage,
  },
  {
    id: 3,
    title: "Data Science Fundamentals",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Explore data analysis, visualization, and machine learning.",
    image: courseImage,
  }, 
  {
    id: 4,
    title: "Graphic Design Mastery",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description:
      "Master design principles with tools like Photoshop and Figma.",
    image: courseImage,
  },
  {
    id: 5,
    title: "Cybersecurity Essentials",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Learn how to protect systems from cyber threats.",
    image: courseImage,
  },
  {
    id: 6,
    title: "Mobile App Development",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Create Android and iOS apps using React Native.",
    image: courseImage,
  },
  {
    id: 7,
    title: "Artificial Intelligence Basics",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Get started with AI, neural networks, and automation.",
    image: courseImage,
  },
  {
    id: 8,
    title: "Digital Marketing Strategy",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Learn SEO, social media marketing, and content strategy.",
    image: courseImage,
  },
  {
    id: 9,
    title: "Project Management",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Become a project leader with Agile and Scrum methodologies.",
    image: courseImage,
  },
  {
    id: 10,
    title: "Entrepreneurship 101",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Turn ideas into successful business ventures.",
    image: courseImage,
  },
  {
    id: 11,
    title: "Photography and Editing",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Capture stunning photos and edit like a pro.",
    image: courseImage,
  },
  {
    id: 12,
    title: "Blockchain and Cryptocurrency",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description:"Understand how blockchain works and explore cryptocurrencies.",
    image: courseImage,
  },
  {
    id: 13,
    title: "Cloud Computing Fundamentals",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Learn about cloud platforms like AWS, Azure, and GCP.",
    image: courseImage,
  },
  {
    id: 14,
    title: "UI/UX Design Principles",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Design user-friendly, beautiful interfaces and experiences.",
    image: courseImage,
  },
  {
    id: 15,
    title: "Game Development",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Create 2D and 3D games with Unity and Unreal Engine.",
    image: courseImage,
  },
  {
    id: 16,
    title: "Advanced JavaScript",
    category: "Mathematics",  
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "50",
    rating: "4.5",
    ratingCount: "75",
    duration: "25 mins",
    description: "Take your JavaScript skills to the next level.",
    image: courseImage,
  },  
];
