import courseImage from "../assets/images/courses/calculus.jpg";
import avater from "../assets/images/courseAuthor/avater.png";

export const courses = [
  {
    id: 1,
    title: "Calculus and Probability",
    category: "Mathematics",
    author: "Dr. Ada Lovelace",
    authorImage: avater,
    totalQuestion: "47",
    rating: "4.0",
    ratingCount: "146",
    duration: "36 mins",
    description: "From basics to advanced topics, this course covers it all in a structured way.",
    image: courseImage,
  },
  {
    id: 2,
    title: "Linear Algebra",
    category: "Cybersecurity",
    author: "Prof. John Doe",
    authorImage: avater,
    totalQuestion: "43",
    rating: "4.9",
    ratingCount: "147",
    duration: "45 mins",
    description: "Learn from experienced instructors and enhance your career opportunities.",
    image: courseImage,
  },
  {
    id: 3,
    title: "Data Structures",
    category: "Biology",
    author: "Ms. Clara Kelvin",
    authorImage: avater,
    totalQuestion: "58",
    rating: "3.9",
    ratingCount: "83",
    duration: "44 mins",
    description: "Master advanced techniques through hands-on projects and in-depth discussions.",
    image: courseImage,
  },
  {
    id: 4,
    title: "Web Development Basics",
    category: "Chemistry",
    author: "Stephen Cred",
    authorImage: avater,
    totalQuestion: "73",
    rating: "5.0",
    ratingCount: "77",
    duration: "43 mins",
    description: "Learn from experienced instructors and enhance your career opportunities.",
    image: courseImage,
  },
  {
    id: 5,
    title: "Advanced Python",
    category: "Engineering",
    author: "Dr. Isaac Newton",
    authorImage: avater,
    totalQuestion: "44",
    rating: "3.8",
    ratingCount: "61",
    duration: "54 mins",
    description: "Explore the foundational principles and practical applications in this comprehensive course.",
    image: courseImage,
  },
  {
    id: 6,
    title: "Machine Learning 101",
    category: "Engineering",
    author: "James Byte",
    authorImage: avater,
    totalQuestion: "59",
    rating: "3.6",
    ratingCount: "132",
    duration: "44 mins",
    description: "Dive into the core concepts and develop the skills needed to solve complex problems.",
    image: courseImage,
  },
  {
    id: 7,
    title: "Database Management",
    category: "Statistics",
    author: "Olivia Fields",
    authorImage: avater,
    totalQuestion: "66",
    rating: "4.4",
    ratingCount: "144",
    duration: "45 mins",
    description: "Learn from experienced instructors and enhance your career opportunities.",
    image: courseImage,
  },
  {
    id: 8,
    title: "Cybersecurity Fundamentals",
    category: "Computer Science",
    author: "Nathan Codewell",
    authorImage: avater,
    totalQuestion: "38",
    rating: "4.8",
    ratingCount: "134",
    duration: "23 mins",
    description: "Learn from experienced instructors and enhance your career opportunities.",
    image: courseImage,
  },
  {
    id: 9,
    title: "Mobile App Development",
    category: "Mathematics",
    author: "Elena Sparks",
    authorImage: avater,
    totalQuestion: "49",
    rating: "3.7",
    ratingCount: "85",
    duration: "29 mins",
    description: "Master advanced techniques through hands-on projects and in-depth discussions.",
    image: courseImage,
  },
  {
    id: 10,
    title: "Cloud Computing",
    category: "Web Development",
    author: "George Boolean",
    authorImage: avater,
    totalQuestion: "30",
    rating: "4.4",
    ratingCount: "44",
    duration: "35 mins",
    description: "Explore the foundational principles and practical applications in this comprehensive course.",
    image: courseImage,
  },
  {
    id: 11,
    title: "Statistics for Beginners",
    category: "Programming",
    author: "Sophia Stack",
    authorImage: avater,
    totalQuestion: "47",
    rating: "3.8",
    ratingCount: "54",
    duration: "32 mins",
    description: "Learn from experienced instructors and enhance your career opportunities.",
    image: courseImage,
  },
  {
    id: 12,
    title: "Discrete Mathematics",
    category: "Cybersecurity",
    author: "Mark Logic",
    authorImage: avater,
    totalQuestion: "61",
    rating: "4.5",
    ratingCount: "74",
    duration: "44 mins",
    description: "Gain valuable skills and industry insights from top professionals in the field.",
    image: courseImage,
  },
  {
    id: 13,
    title: "Artificial Intelligence",
    category: "Mathematics",
    author: "Laura Pascal",
    authorImage: avater,
    totalQuestion: "79",
    rating: "4.3",
    ratingCount: "64",
    duration: "21 mins",
    description: "Dive into the core concepts and develop the skills needed to solve complex problems.",
    image: courseImage,
  },
  {
    id: 14,
    title: "Software Engineering",
    category: "Cybersecurity",
    author: "Terry Lambda",
    authorImage: avater,
    totalQuestion: "32",
    rating: "3.7",
    ratingCount: "101",
    duration: "55 mins",
    description: "Learn from experienced instructors and enhance your career opportunities.",
    image: courseImage,
  },
  {
    id: 15,
    title: "Network Essentials",
    category: "Software Development",
    author: "Nina Networks",
    authorImage: avater,
    totalQuestion: "69",
    rating: "3.5",
    ratingCount: "79",
    duration: "28 mins",
    description: "A beginner-friendly course with step-by-step instructions and real-world examples.",
    image: courseImage,
  },
  {
    id: 16,
    title: "HTML & CSS Bootcamp",
    category: "Data Science",
    author: "Isaiah Token",
    authorImage: avater,
    totalQuestion: "69",
    rating: "4.5",
    ratingCount: "43",
    duration: "52 mins",
    description: "Learn from experienced instructors and enhance your career opportunities.",
    image: courseImage,
  },
  {
    id: 17,
    title: "JavaScript Deep Dive",
    category: "Engineering",
    author: "Clara Vision",
    authorImage: avater,
    totalQuestion: "69",
    rating: "3.9",
    ratingCount: "119",
    duration: "26 mins",
    description: "Master advanced techniques through hands-on projects and in-depth discussions.",
    image: courseImage,
  },
  {
    id: 18,
    title: "React for Beginners",
    category: "Engineering",
    author: "Fred Loop",
    authorImage: avater,
    totalQuestion: "57",
    rating: "4.9",
    ratingCount: "42",
    duration: "54 mins",
    description: "From basics to advanced topics, this course covers it all in a structured way.",
    image: courseImage,
  },
  {
    id: 19,
    title: "Intro to Algorithms",
    category: "Programming",
    author: "Anita Pointer",
    authorImage: avater,
    totalQuestion: "72",
    rating: "3.5",
    ratingCount: "123",
    duration: "50 mins",
    description: "Perfect for those looking to enhance their knowledge and gain practical experience.",
    image: courseImage,
  },
  {
    id: 20,
    title: "Version Control with Git",
    category: "AI & ML",
    author: "Tommy Types",
    authorImage: avater,
    totalQuestion: "72",
    rating: "4.0",
    ratingCount: "56",
    duration: "22 mins",
    description: "Get started on your tech journey with this essential and engaging course.",
    image: courseImage,
  }
];


export const categoryStyles = {
  "Mathematics": {
    bg: "bg-green-100",
    text: "text-green-600"
  },
  "Biology": {
    bg: "bg-purple-100",
    text: "text-purple-600"
  },
  "Chemistry": {
    bg: "bg-pink-100",
    text: "text-pink-600"
  },
  "Physics": {
    bg: "bg-yellow-100",
    text: "text-yellow-600"
  },
  "English": {
    bg: "bg-blue-100",
    text: "text-blue-600"
  },
  "General Knowledge": {
    bg: "bg-red-100",
    text: "text-red-600"
  },
  // fallback
  "default": {
    bg: "bg-gray-100",
    text: "text-gray-600"
  }
};
