import folder from '../assets/images/courses/folder.png';
import doc from "../assets/images/courses/doc.png";
import xls from "../assets/images/courses/xls.png";
import pdf from "../assets/images/courses/pdf.png";


export const resourceContents = [    
    { id: 1, icon: folder, type: 'folder', title: 'Chemistry', files: 20, path: '../assets/files/service.txt' },
    { id: 2, icon: folder, type: 'folder', title: 'Physics', files: 12, path: '../assets/files/service.txt' },
    { id: 3, icon: folder, type: 'folder', title: 'Economics', files: 15, path: '../assets/files/service.txt' },
    { id: 4, icon: folder, type: 'folder', title: 'Mathematics', files: 8, path: '../assets/files/service.txt' },
    { id: 5, icon: folder, type: 'folder', title: 'AI Intro', files: 10, path: '../assets/files/service.txt' },
    { id: 6, icon: folder, type: 'folder', title: 'BIology', files: 14, path: '../assets/files/service.txt' },
    { id: 7, icon: xls, type: 'xls', title: 'DevOps', path: '../assets/files/service.txt' },
    { id: 8, icon: xls, type: 'xls', title: 'Mobile Dev', path: '../assets/files/service.txt' },
    { id: 9, icon: pdf, type: 'pdf', title: 'Data Science', path: '../assets/files/service.txt' },
    { id: 10, icon: doc, type: 'doc', title: 'Cloud Computing', path: '../assets/files/service.txt' },
    { id: 11, icon: folder, type: 'folder', title: 'Cybersecurity', files: 16, path: '../assets/files/service.txt' },
    { id: 12, icon: pdf, type: 'pdf', title: 'Machine Learning', path: '../assets/files/service.txt' },
    { id: 13, icon: folder, type: 'folder', title: 'Chemistry', files: 20, path: '../assets/files/service.txt' },
    { id: 14, icon: pdf, type: 'pdf', title: 'Physics', path: '../assets/files/service.txt' },
    { id: 15, icon: folder, type: 'folder', title: 'Economics', files: 15, path: '../assets/files/service.txt' },
    { id: 16, icon: pdf, type: 'pdf', title: 'Mathematics', path: '../assets/files/service.txt' },
    { id: 17, icon: doc, type: 'doc', title: 'AI Intro', path: '../assets/files/service.txt' },
    { id: 18, icon: folder, type: 'folder', title: 'BIology', files: 14, path: '../assets/files/service.txt' },
    { id: 19, icon: xls, type: 'xls', title: 'DevOps', path: '../assets/files/service.txt' },
    { id: 20, icon: doc, type: 'doc', title: 'Mobile Dev', path: '../assets/files/service.txt' },
    { id: 21, icon: folder, type: 'folder', title: 'Data Science', files: 18, path: '../assets/files/service.txt' },
    { id: 22, icon: pdf, type: 'pdf', title: 'Cloud Computing', path: '../assets/files/service.txt' },
    { id: 23, icon: folder, type: 'folder', title: 'Cybersecurity', files: 16, path: '../assets/files/service.txt' },
    { id: 24, icon: pdf, type: 'pdf', title: 'Machine Learning', path: '../assets/files/service.txt' },
    { id: 25, icon: folder, type: 'folder', title: 'Chemistry', files: 20, path: '../assets/files/service.txt' },
    { id: 26, icon: doc, type: 'doc', title: 'Physics', path: '../assets/files/service.txt' },
    { id: 27, icon: folder, type: 'folder', title: 'Economics', files: 15, path: '../assets/files/service.txt' },
    { id: 28, icon: xls, type: 'xls', title: 'Mathematics', path: '../assets/files/service.txt' },
    { id: 29, icon: doc, type: 'doc', title: 'AI Intro', path: '../assets/files/service.txt' },
    { id: 30, icon: folder, type: 'folder', title: 'BIology', files: 14, path: '../assets/files/service.txt' },
    { id: 31, icon: pdf, type: 'pdf', title: 'DevOps', path: '../assets/files/service.txt' },
    { id: 32, icon: pdf, type: 'pdf', title: 'Mobile Dev', path: '../assets/files/service.txt' },
    { id: 33, icon: folder, type: 'folder', title: 'Data Science', files: 18, path: '../assets/files/service.txt' },
    { id: 34, icon: pdf, type: 'pdf', title: 'Cloud Computing', path: '../assets/files/service.txt' },
    { id: 35, icon: folder, type: 'folder', title: 'Cybersecurity', files: 16, path: '../assets/files/service.txt' },
    { id: 36, icon: pdf, type: 'pdf', title: 'Machine Learning', path: '../assets/files/service.txt' },
    { id: 37, icon: folder, type: 'folder', title: 'Chemistry', files: 20, path: '../assets/files/service.txt' },
    { id: 38, icon: pdf, type: 'pdf', title: 'Physics', path: '../assets/files/service.txt' },
    { id: 39, icon: folder, type: 'folder', title: 'Economics', files: 15, path: '../assets/files/service.txt' },
    { id: 40, icon: pdf, type: 'pdf', title: 'Mathematics', path: '../assets/files/service.txt' },
    { id: 41, icon: doc, type: 'doc', title: 'AI Intro', path: '../assets/files/service.txt' },
    { id: 42, icon: folder, type: 'folder', title: 'BIology', files: 14, path: '../assets/files/service.txt' },
    { id: 43, icon: pdf, type: 'pdf', title: 'DevOps', path: '../assets/files/service.txt' },
    { id: 44, icon: pdf, type: 'pdf', title: 'Mobile Dev', path: '../assets/files/service.txt' },
    { id: 45, icon: folder, type: 'folder', title: 'Data Science', files: 18, path: '../assets/files/service.txt' },
    { id: 46, icon: pdf, type: 'pdf', title: 'Cloud Computing', path: '../assets/files/service.txt' },
    { id: 47, icon: folder, type: 'folder', title: 'Cybersecurity', files: 16, path: '../assets/files/service.txt' },
    { id: 48, icon: pdf, type: 'pdf', title: 'Machine Learning', path: '../assets/files/service.txt' },
    { id: 49, icon: folder, type: 'folder', title: 'Chemistry', files: 20, path: '../assets/files/service.txt' },
    { id: 50, icon: doc, type: 'doc', title: 'Physics', path: '../assets/files/service.txt' },
    { id: 51, icon: folder, type: 'folder', title: 'Economics', files: 15, path: '../assets/files/service.txt' },
    { id: 52, icon: xls, type: 'xls', title: 'Mathematics', path: '../assets/files/service.txt' },
    { id: 53, icon: doc, type: 'doc', title: 'AI Intro', path: '../assets/files/service.txt' },
    { id: 54, icon: folder, type: 'folder', title: 'BIology', files: 14, path: '../assets/files/service.txt' },
    { id: 55, icon: pdf, type: 'pdf', title: 'DevOps', path: '../assets/files/service.txt' },
    { id: 56, icon: pdf, type: 'pdf', title: 'Mobile Dev', path: '../assets/files/service.txt' },
    { id: 57, icon: folder, type: 'folder', title: 'Data Science', files: 18, path: '../assets/files/service.txt' },
    { id: 58, icon: pdf, type: 'pdf', title: 'Cloud Computing', path: '../assets/files/service.txt' },
    { id: 59, icon: folder, type: 'folder', title: 'Cybersecurity', files: 16, path: '../assets/files/service.txt' },
    { id: 60, icon: pdf, type: 'pdf', title: 'Machine Learning', path: '../assets/files/service.txt' },
    { id: 61, icon: folder, type: 'folder', title: 'Chemistry', files: 20, path: '../assets/files/service.txt' },
    { id: 62, icon: doc, type: 'doc', title: 'Physics', path: '../assets/files/service.txt' },
    { id: 63, icon: folder, type: 'folder', title: 'Economics', files: 15, path: '../assets/files/service.txt' },
    { id: 64, icon: doc, type: 'doc', title: 'Mathematics', path: '../assets/files/service.txt' },
    { id: 65, icon: doc, type: 'doc', title: 'AI Intro', path: '../assets/files/service.txt' },
    { id: 66, icon: folder, type: 'folder', title: 'BIology', files: 14, path: '../assets/files/service.txt' },
    { id: 67, icon: pdf, type: 'pdf', title: 'DevOps', path: '../assets/files/service.txt' },
    { id: 68, icon: pdf, type: 'pdf', title: 'Mobile Dev', path: '../assets/files/service.txt' },
    { id: 69, icon: folder, type: 'folder', title: 'Data Science', files: 18, path: '../assets/files/service.txt' },
    { id: 70, icon: pdf, type: 'pdf', title: 'Cloud Computing', path: '../assets/files/service.txt' },
    { id: 71, icon: folder, type: 'folder', title: 'Cybersecurity', files: 16, path: '../assets/files/service.txt' },
    { id: 72, icon: pdf, type: 'pdf', title: 'Machine Learning', path: '../assets/files/service.txt' },
];