import questionimage from '../assets/images/questionimage.jpg';



export const testquestions = [
  {
    id: 1,
    question: "What is the capital of France?",
    options: [
      { option: "A", answer: "Paris" },
      { option: "B", answer: "London" },
      { option: "C", answer: "Berlin" },
      { option: "D", answer: "Madrid" },
    ],
    answer: "A",
    explanation: "Paris is the capital of France.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 2,
    question: "What is 2 + 2?",
    options: [
      { option: "A", answer: "3" },
      { option: "B", answer: "4" },
      { option: "C", answer: "5" },
      { option: "D", answer: "6" },
    ],
    answer: "B",
    explanation: "2 + 2 equals 4.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 3,
    question: "Which planet is known as the Red Planet?",
    options: [
      { option: "A", answer: "Earth" },
      { option: "B", answer: "Mars" },
      { option: "C", answer: "Jupiter" },
      { option: "D", answer: "Venus" },
    ],
    answer: "B",
    explanation:
      "Mars is known as the Red Planet due to its reddish appearance.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 4,
    question: "What is the chemical symbol for water?",
    options: [
      { option: "A", answer: "O2" },
      { option: "B", answer: "H2O" },
      { option: "C", answer: "CO2" },
      { option: "D", answer: "NaCl" },
    ],
    answer: "B",
    explanation: "H2O is the chemical formula for water.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 5,
    question: "Identify the animal in the image.",
    options: [
      { option: "A", answer: "Lion" },
      { option: "B", answer: "Tiger" },
      { option: "C", answer: "Elephant" },
      { option: "D", answer: "Giraffe" },
    ],
    answer: "A",
    explanation:
      "The image shows a lion, which is known as the king of the jungle.",
    marks: 1,
    questionimage: questionimage,
  },
  {
    id: 6,
    question: "What is the largest ocean on Earth?",
    options: [
      { option: "A", answer: "Atlantic Ocean" },
      { option: "B", answer: "Indian Ocean" },
      { option: "C", answer: "Pacific Ocean" },
      { option: "D", answer: "Arctic Ocean" },
    ],
    answer: "C",
    explanation: "The Pacific Ocean is the largest ocean on Earth.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 7,
    question: "What is the boiling point of water at sea level?",
    options: [
      { option: "A", answer: "90°C" },
      { option: "B", answer: "100°C" },
      { option: "C", answer: "110°C" },
      { option: "D", answer: "120°C" },
    ],
    answer: "B",
    explanation: "Water boils at 100°C at sea level.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 8,
    question: "Which country is known as the Land of the Rising Sun?",
    options: [
      { option: "A", answer: "China" },
      { option: "B", answer: "Japan" },
      { option: "C", answer: "South Korea" },
      { option: "D", answer: "Thailand" },
    ],
    answer: "B",
    explanation: "Japan is known as the Land of the Rising Sun.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 9,
    question: "What is the square root of 64?",
    options: [
      { option: "A", answer: "6" },
      { option: "B", answer: "7" },
      { option: "C", answer: "8" },
      { option: "D", answer: "9" },
    ],
    answer: "C",
    explanation: "The square root of 64 is 8.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 10,
    question: "Identify the structure in the image.",
    options: [
      { option: "A", answer: "Eiffel Tower" },
      { option: "B", answer: "Statue of Liberty" },
      { option: "C", answer: "Big Ben" },
      { option: "D", answer: "Colosseum" },
    ],
    answer: "A",
    explanation: "The image shows the Eiffel Tower, located in Paris, France.",
    marks: 1,
    questionimage: questionimage,
  },
  {
    id: 11,
    question: "What is the capital of France?",
    options: [
      { option: "A", answer: "Paris" },
      { option: "B", answer: "London" },
      { option: "C", answer: "Berlin" },
      { option: "D", answer: "Madrid" },
    ],
    answer: "A",
    explanation: "Paris is the capital of France.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 12,
    question: "What is 2 + 2?",
    options: [
      { option: "A", answer: "3" },
      { option: "B", answer: "4" },
      { option: "C", answer: "5" },
      { option: "D", answer: "6" },
    ],
    answer: "B",
    explanation: "2 + 2 equals 4.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 13,
    question: "Which planet is known as the Red Planet?",
    options: [
      { option: "A", answer: "Earth" },
      { option: "B", answer: "Mars" },
      { option: "C", answer: "Jupiter" },
      { option: "D", answer: "Venus" },
    ],
    answer: "B",
    explanation:
      "Mars is known as the Red Planet due to its reddish appearance.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 14,
    question: "What is the chemical symbol for water?",
    options: [
      { option: "A", answer: "O2" },
      { option: "B", answer: "H2O" },
      { option: "C", answer: "CO2" },
      { option: "D", answer: "NaCl" },
    ],
    answer: "B",
    explanation: "H2O is the chemical formula for water.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 15,
    question: "Identify the animal in the image.",
    options: [
      { option: "A", answer: "Lion" },
      { option: "B", answer: "Tiger" },
      { option: "C", answer: "Elephant" },
      { option: "D", answer: "Giraffe" },
    ],
    answer: "A",
    explanation:
      "The image shows a lion, which is known as the king of the jungle.",
    marks: 1,
    questionimage: questionimage,
  },
  {
    id: 16,
    question: "What is the largest ocean on Earth?",
    options: [
      { option: "A", answer: "Atlantic Ocean" },
      { option: "B", answer: "Indian Ocean" },
      { option: "C", answer: "Pacific Ocean" },
      { option: "D", answer: "Arctic Ocean" },
    ],
    answer: "C",
    explanation: "The Pacific Ocean is the largest ocean on Earth.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 17,
    question: "What is the boiling point of water at sea level?",
    options: [
      { option: "A", answer: "90°C" },
      { option: "B", answer: "100°C" },
      { option: "C", answer: "110°C" },
      { option: "D", answer: "120°C" },
    ],
    answer: "B",
    explanation: "Water boils at 100°C at sea level.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 18,
    question: "Which country is known as the Land of the Rising Sun?",
    options: [
      { option: "A", answer: "China" },
      { option: "B", answer: "Japan" },
      { option: "C", answer: "South Korea" },
      { option: "D", answer: "Thailand" },
    ],
    answer: "B",
    explanation: "Japan is known as the Land of the Rising Sun.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 19,
    question: "What is the square root of 64?",
    options: [
      { option: "A", answer: "6" },
      { option: "B", answer: "7" },
      { option: "C", answer: "8" },
      { option: "D", answer: "9" },
    ],
    answer: "C",
    explanation: "The square root of 64 is 8.",
    marks: 1,
    questionimage: null,
  },
  {
    id: 20,
    question: "Identify the structure in the image.",
    options: [
      { option: "A", answer: "Eiffel Tower" },
      { option: "B", answer: "Statue of Liberty" },
      { option: "C", answer: "Big Ben" },
      { option: "D", answer: "Colosseum" },
    ],
    answer: "A",
    explanation: "The image shows the Eiffel Tower, located in Paris, France.",
    marks: 1,
    questionimage: questionimage,
  },
];
