export const studentsData = [
    {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
      enrolledDate: "2025-03-01",
      progress: "80%",
      score: "48/60",
      status: "In Progress",
    },
    {
      id: "2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      enrolledDate: "2025-03-02",
      progress: "100%",
      score: "60/60",
      status: "Completed",
    },
    {
      id: "3",
      name: "Michael Johnson",
      email: "michael.johnson@example.com",
      enrolledDate: "2025-03-03",
      progress: "70%",
      score: "42/60",
      status: "In Progress",
    },
    {
      id: "4",
      name: "Emily Davis",
      email: "emily.davis@example.com",
      enrolledDate: "2025-03-04",
      progress: "90%",
      score: "54/60",
      status: "In Progress",
    },
    {
      id: "5",
      name: "Daniel Brown",
      email: "daniel.brown@example.com",
      enrolledDate: "2025-03-05",
      progress: "100%",
      score: "60/60",
      status: "Completed",
    },
    {
      id: "6",
      name: "Sophia Williams",
      email: "sophia.williams@example.com",
      enrolledDate: "2025-03-06",
      progress: "50%",
      score: "30/60",
      status: "In Progress",
    },
    {
      id: "7",
      name: "James Wilson",
      email: "james.wilson@example.com",
      enrolledDate: "2025-03-07",
      progress: "60%",
      score: "36/60",
      status: "In Progress",
    },
    {
      id: "8",
      name: "Olivia Martinez",
      email: "olivia.martinez@example.com",
      enrolledDate: "2025-03-08",
      progress: "80%",
      score: "48/60",
      status: "In Progress",
    },
    {
      id: "9",
      name: "Lucas Garcia",
      email: "lucas.garcia@example.com",
      enrolledDate: "2025-03-09",
      progress: "90%",
      score: "54/60",
      status: "In Progress",
    },
    {
      id: "10",
      name: "Ava Taylor",
      email: "ava.taylor@example.com",
      enrolledDate: "2025-03-10",
      progress: "100%",
      score: "60/60",
      status: "Completed",
    },
  ];
  